/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alexis' at '17/02/16 09:34' with Gradle 2.6
 *
 * @author Alexis, @date 17/02/16 09:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
